#!/bin/bash

set -e

VERSION="1.0.0"
IMAGE_BACKEND="ghcr.io/whoshotu/dr-code-v2-backend:latest"
IMAGE_FRONTEND="ghcr.io/whoshotu/dr-code-v2-frontend:latest"
PORTS=(3001 8002 27017)
COMPOSE_FILE="docker-compose.yml"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

detect_os() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "macos"
    elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || [[ "$OSTYPE" == "win32" ]]; then
        echo "windows"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if grep -qEi "(Microsoft|WSL)" /proc/version 2>/dev/null; then
            echo "wsl"
        else
            echo "linux"
        fi
    else
        echo "unknown"
    fi
}

check_docker() {
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed."
        echo "Install Docker: https://docs.docker.com/get-docker/"
        exit 1
    fi
    
    if ! command -v docker compose &> /dev/null && ! docker-compose --version &> /dev/null; then
        log_error "Docker Compose is not installed."
        echo "Install Docker Compose: https://docs.docker.com/compose/install/"
        exit 1
    fi
    
    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running."
        echo "Start Docker and try again."
        exit 1
    fi
    
    log_info "Docker is ready"
}

check_ports() {
    log_info "Checking ports..."
    INUSE=()
    for PORT in "${PORTS[@]}"; do
        if command -v lsof &> /dev/null; then
            if lsof -i:$PORT &> /dev/null; then
                INUSE+=($PORT)
            fi
        elif command -v netstat &> /dev/null; then
            if netstat -tuln 2>/dev/null | grep -q ":$PORT "; then
                INUSE+=($PORT)
            fi
        fi
    done
    
    if [ ${#INUSE[@]} -gt 0 ]; then
        log_warn "Ports in use: ${INUSE[*]}"
        log_warn "Services may fail to start."
        echo "Stop other services or change ports in docker-compose.yml"
    else
        log_info "All ports available"
    fi
}

create_config() {
    if [ ! -f ".env.docker" ]; then
        log_info "Creating configuration..."
        cat > .env.docker << 'EOF'
# DR.CODE-v2 Docker Configuration
# Auto-generated by install.sh

# MongoDB: Auto-detected (docker network)
# MONGO_URL=mongodb://mongo:27017/drcode

# Ollama: Auto-detected from host
# OLLAMA_BASE_URL=http://host.docker.internal:11434
# OLLAMA_MODEL=codellama

# Database
DB_NAME=drcode

# CORS
CORS_ORIGINS=http://localhost:3001
EOF
        log_info "Configuration created"
    else
        log_info "Configuration already exists"
    fi
}

pull_images() {
    log_info "Pulling Docker images..."
    docker pull $IMAGE_BACKEND || log_warn "Failed to pull backend image"
    docker pull $IMAGE_FRONTEND || log_warn "Failed to pull frontend image"
    log_info "Images ready"
}

start_services() {
    log_info "Starting services..."
    if command -v docker compose &> /dev/null; then
        docker compose up -d
    else
        docker-compose up -d
    fi
}

stop_services() {
    log_info "Stopping services..."
    if command -v docker compose &> /dev/null; then
        docker compose down
    else
        docker-compose down
    fi
}

clean_services() {
    log_info "Removing services and volumes..."
    if command -v docker compose &> /dev/null; then
        docker compose down -v
    else
        docker-compose down -v
    fi
}

show_status() {
    echo ""
    echo "=========================================="
    echo "  DR.CODE v2 Status"
    echo "=========================================="
    echo ""
    
    if command -v docker compose &> /dev/null; then
        docker compose ps
    else
        docker-compose ps
    fi
    
    echo ""
    echo "URLs:"
    echo "  Frontend: http://localhost:3001"
    echo "  Backend:  http://localhost:8002"
    echo "  API:      http://localhost:8002/api"
    echo ""
}

show_help() {
    echo "DR.CODE v2 Installer v$VERSION"
    echo ""
    echo "Usage: $0 [command]"
    echo ""
    echo "Commands:"
    echo "  install   (default)  Install and start services"
    echo "  start              Start services"
    echo "  stop               Stop services"
    echo "  status             Show service status"
    echo "  update             Pull latest images"
    echo "  clean              Stop and remove all data"
    echo "  help               Show this help"
    echo ""
    echo "Ports: 3001 (frontend), 8002 (backend), 27017 (mongodb)"
}

case "${1:-install}" in
    install)
        check_docker
        check_ports
        create_config
        pull_images
        start_services
        show_status
        log_info "Installation complete!"
        ;;
    start)
        check_docker
        start_services
        show_status
        ;;
    stop)
        stop_services
        log_info "Services stopped"
        ;;
    status)
        show_status
        ;;
    update)
        check_docker
        pull_images
        stop_services
        start_services
        show_status
        log_info "Update complete!"
        ;;
    clean)
        clean_services
        log_info "All data removed"
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        log_error "Unknown command: $1"
        show_help
        exit 1
        ;;
esac
