$VERSION = "1.0.0"
$IMAGE_BACKEND = "ghcr.io/whoshotu/dr-code-v2-backend:latest"
$IMAGE_FRONTEND = "ghcr.io/whoshotu/dr-code-v2-frontend:latest"
$PORTS = @(3001, 8002, 27017)

function Write-Info { param($msg) Write-Host "[INFO] $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Write-Error { param($msg) Write-Host "[ERROR] $msg" -ForegroundColor Red }

function Test-Docker {
    $docker = Get-Command docker -ErrorAction SilentlyContinue
    if (-not $docker) {
        Write-Error "Docker is not installed."
        Write-Host "Install Docker: https://docs.docker.com/get-docker/"
        exit 1
    }
    
    try {
        docker info 2>$null | Out-Null
    } catch {
        Write-Error "Docker daemon is not running."
        Write-Host "Start Docker Desktop and try again."
        exit 1
    }
    
    Write-Info "Docker is ready"
}

function Test-Ports {
    Write-Info "Checking ports..."
    $inUse = @()
    
    foreach ($port in $PORTS) {
        $connection = Test-NetConnection -ComputerName localhost -Port $port -WarningAction SilentlyContinue -ErrorAction SilentlyContinue
        if ($connection.TcpTestSucceeded) {
            $inUse += $port
        }
    }
    
    if ($inUse.Count -gt 0) {
        Write-Warn "Ports in use: $($inUse -join ', ')"
        Write-Warn "Services may fail to start."
    } else {
        Write-Info "All ports available"
    }
}

function New-Config {
    if (-not (Test-Path ".env.docker")) {
        Write-Info "Creating configuration..."
        @"
# DR.CODE-v2 Docker Configuration
# Auto-generated by install.ps1

# MongoDB: Auto-detected (docker network)
# MONGO_URL=mongodb://mongo:27017/drcode

# Ollama: Auto-detected from host
# OLLAMA_BASE_URL=http://host.docker.internal:11434
# OLLAMA_MODEL=codellama

# Database
DB_NAME=drcode

# CORS
CORS_ORIGINS=http://localhost:3001
"@ | Out-File -FilePath ".env.docker" -Encoding UTF8
        Write-Info "Configuration created"
    } else {
        Write-Info "Configuration already exists"
    }
}

function Start-Install {
    Test-Docker
    Test-Ports
    New-Config
    
    Write-Info "Pulling Docker images..."
    docker pull $IMAGE_BACKEND 2>$null || Write-Warn "Failed to pull backend image"
    docker pull $IMAGE_FRONTEND 2>$null || Write-Warn "Failed to pull frontend image"
    Write-Info "Images ready"
    
    Write-Info "Starting services..."
    docker compose up -d 2>$null || docker-compose up -d
    Show-Status
    Write-Info "Installation complete!"
}

function Start-Services {
    Test-Docker
    docker compose up -d 2>$null || docker-compose up -d
    Show-Status
}

function Stop-Services {
    Write-Info "Stopping services..."
    docker compose down 2>$null || docker-compose down
    Write-Info "Services stopped"
}

function Show-Status {
    Write-Host ""
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host "  DR.CODE v2 Status" -ForegroundColor Cyan
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host ""
    
    docker compose ps 2>$null || docker-compose ps
    
    Write-Host ""
    Write-Host "URLs:" -ForegroundColor Cyan
    Write-Host "  Frontend: http://localhost:3001"
    Write-Host "  Backend:  http://localhost:8002"
    Write-Host "  API:      http://localhost:8002/api"
    Write-Host ""
}

function Update-Services {
    Test-Docker
    
    Write-Info "Pulling latest images..."
    docker pull $IMAGE_BACKEND 2>$null || Write-Warn "Failed to pull backend"
    docker pull $IMAGE_FRONTEND 2>$null || Write-Warn "Failed to pull frontend"
    
    Stop-Services
    Start-Services
    Write-Info "Update complete!"
}

function Clear-Services {
    Write-Info "Removing services and volumes..."
    docker compose down -v 2>$null || docker-compose down -v
    Write-Info "All data removed"
}

function Show-Help {
    Write-Host "DR.CODE v2 Installer v$VERSION" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Usage: .\install.ps1 [command]" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Commands:" -ForegroundColor Cyan
    Write-Host "  install   (default)  Install and start services"
    Write-Host "  start              Start services"
    Write-Host "  stop               Stop services"
    Write-Host "  status             Show service status"
    Write-Host "  update             Pull latest images"
    Write-Host "  clean              Stop and remove all data"
    Write-Host "  help               Show this help"
    Write-Host ""
    Write-Host "Ports: 3001 (frontend), 8002 (backend), 27017 (mongodb)" -ForegroundColor Gray
}

$command = $args[0]
if (-not $command) { $command = "install" }

switch ($command.ToLower()) {
    "install" { Start-Install }
    "start" { Start-Services }
    "stop" { Stop-Services }
    "status" { Show-Status }
    "update" { Update-Services }
    "clean" { Clear-Services }
    "help" { Show-Help }
    default { Write-Error "Unknown command: $command"; Show-Help; exit 1 }
}
